<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="addressbookservice.AddressBookServiceTest" tests="1" skipped="0" failures="0" errors="0" timestamp="2020-12-20T16:46:59" hostname="ADMIN-PC" time="6.076">
  <properties/>
  <testcase name="givenDateRangeWhenRetrieved_ShouldMatchEntryCount" classname="addressbookservice.AddressBookServiceTest" time="6.076"/>
  <system-out><![CDATA[Connectinng to database:jdbc:mysql://localhost:3306/addressbook_service?useSSL=false
Connection is successful!!!com.mysql.jdbc.JDBC4Connection@1175eed
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
